apiVersion: v1
kind: Service
metadata:
  name: kibosh-bazaar-np
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - targetPort: 8081
      protocoll: TCP
      port: 8081
  selector:
    name: kibosh


