apiVersion: v1
kind: Service
metadata:
  name: kibosh-np
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      protocoll: TCP
      port: 8080
  selector:
    name: kibosh


