apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibosh
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kibosh
  replicas: 1
  template:
    metadata:
      labels:
        name: kibosh
    spec:
      serviceAccount: kibosh-helm
      containers:
      - name: kibosh
        image: nouseforaname/kibosh:latest
        imagePullPolicy: Always
        command: ["start"]
        ports:
        - containerPort: 8080
        - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        env:
        - name: BAZAAR_USER
          valueFrom:
            configMapKeyRef:
             # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: cluster-addon-deployment-data
              key: bazaar.user
        - name: BAZAAR_PASSWORD
          valueFrom:
            configMapKeyRef:
             # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: cluster-addon-deployment-data
              key: bazaar.password
        - name: KIBOSH_USER
          valueFrom:
            configMapKeyRef:
             # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: cluster-addon-deployment-data
              key: kibosh.user
        - name: KIBOSH_PASSWORD
          valueFrom:
            configMapKeyRef:
             # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: cluster-addon-deployment-data
              key: kibosh.password
        
          