Spring:
 profiles:
  include: default
  active: dev

pks:
  fqdn: api.pks.pcf21.starkandwayne.com
  apps_tcp_fqdn: apps.tcp.pks.pcf21.starkandwayne.com
  pks_api_user: 
    name: 
    password: 
  pks_api_client:
    accessTokenUri: https://api.pks.pcf21.starkandwayne.com:8443/oauth/token
    name: pks_cli
    secret: ""
    grant_type: password
    
spring:
  profile: default
  security:
    user:
      name: admin
      password: pass
      roles: ADMIN
  application:
    name: PKS-Broker
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: PKS-Service
          name: PKS-Service
          description: Deploy On Demand PKS Clusters
          bindable: true
          bindings_retrievable: true
          tags:
          - PKS
          - Kubernetes
          plans:
          - id: small
            name: small
            description: |
              small Cluster with 1 Master 3 Workers
              More Description
          - id: medium
            name: medium
            description: |
              medium Cluster with 1 Master 5 Workers
              More Description
          - id: large
            name: large
            description: |
              large Cluster with 1 Master 10 Workers
              More Description
