---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "latest"

inputs:
- name: osb-pks
- name: version

outputs:
- name: jar

run:
  path: osb-pks-ci/ci/tasks/maven-build.sh
