---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: nouseforaname/jdk-8-netcat-jq
    tag: "latest"

inputs:
- name: osb-pks-ci
- name: jar

outputs:

params:
  SPRING_APPLICATION_JSON:
  PCF_CA_CERT:
  SKIP_TLS:
  HOSTS:

run:
  path: osb-pks-ci/ci/tasks/run-test-update-deploy-default-operators.sh

