---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: nouseforaname/jdk-8-netcat-jq
    tag: "latest"

inputs:
- name: sb_source
- name: jar

outputs:

params:
  SPRING_APPLICATION_JSON:
  PCF_CA_CERT:

run:
  path: sb_source/ci/tasks/run-tests.sh

