---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: nouseforaname/jdk-8-netcat-jq
    tag: "latest"

inputs:
- name: version
- name: osb-pks-ci
- name: osb-pks-pre-release
- name: test-cluster-data

outputs:

params:
  SPRING_APPLICATION_JSON:
  PCF_CA_CERT:
  SKIP_TLS:
  HOSTS:
  CHART_TGZ_PATH:
  CHART_TEST_SCRIPT_PATH:

run:
  path: osb-pks-ci/ci/tasks/upload-and-test-chart.sh

