jobs:
- name: create-latest-build
  plan:
  - aggregate:
    - get: version
      params: {bump: minor}
    - get: osb-pks
    - get: osb-pks-ci
  - task: maven-build
    file: osb-pks-ci/ci/tasks/maven-build.yml
  - put: version
    params: 
      bump: patch
  - put: osb-pks-pre-release
    params:
      name: version/version
      tag: version/version
      body: jar/body
      globs:
      - jar/osb_pks.jar
- name: run-tests
  plan:
  - aggregate:
    - get: osb-pks-ci
    - get: version
      passed: 
      - create-latest-build
    - get: osb-pks-pre-release
      passed: 
      - create-latest-build
  - task: run-test-create-empty-cluster
    file: osb-pks-ci/ci/tasks/run-test-create-empty-cluster.yml
    params:
      SPRING_APPLICATION_JSON: ((spring_application_json))
      SKIP_TLS: true
      PCF_CA_CERT: ((pcf_ca))
      HOSTS: 
      - 10.213.10.52 tcp.pcf21.starkandwayne.com
      - 10.213.10.3 api.pks.pcf21.starkandwayne.com
  - task: run-test-update-deploy-kibosh
    file: osb-pks-ci/ci/tasks/run-test-update-deploy-kibosh.yml
    params:
      SPRING_APPLICATION_JSON: ((spring_application_json))
      SKIP_TLS: true
      PCF_CA_CERT: ((pcf_ca))
      HOSTS: 
      - 10.213.10.52 tcp.pcf21.starkandwayne.com
      - 10.213.10.3 api.pks.pcf21.starkandwayne.com
  - put: osb-pks-release
    params:
      name: version/version
      tag: version/version
      globs:
      - osb-pks-pre-release/osb_pks.jar
    
resources:
- name: osb-pks
  type: git
  source:
    branch: master
    uri: git@github.com:starkandwayne/osb-pks.git
    private_key: ((git_key))
    paths:
    - src/**/*
- name: osb-pks-ci
  type: git
  source:
    branch: master
    uri: git@github.com:starkandwayne/osb-pks.git
    private_key: ((git_key))
    paths:
    - ci/**/*
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:starkandwayne/osb-pks.git
    branch: master
    file: version
    private_key: ((git_key))
    initial_version: 0.0.1
- name: osb-pks-release
  type: github-release
  source:
    owner: starkandwayne
    repository: osb-pks
    private_key: ((git_key))
    access_token: ((osb-pks-repo-access-token))
- name: osb-pks-pre-release
  type: github-release
  source:
    owner: starkandwayne
    repository: osb-pks
    pre_release: true
    private_key: ((git_key))
    access_token: ((osb-pks-repo-access-token))
