jobs:
- name: create-latest-build
  plan:
  - aggregate:
    - get: osb-pks
  - task: maven-build
    file: osb-pks/ci/tasks/maven-build.yml
    - put: 
- name: run-tests
  plan:
  - aggregate:
    - get: osb-pks

  - task: run-test-create-empty-cluster
    file: osb-psk/ci/tasks/run-test-create-empty-cluster.yml
    params:
      SPRING_APPLICATION_JSON: ((spring_application_json))
      SKIP_TLS: true
      HOSTS: |
        10.213.10.52 tcp.pcf21.starkandwayne.com
        10.213.10.3 api.pks.pcf21.starkandwayne.coma
  - task: run-test-update-deploy-kibosh
    file: osb-psk/ci/tasks/run-test-update-deploy-kibosh.yml
    params:
      SPRING_APPLICATION_JSON: ((spring_application_json))
      SKIP_TLS: true
      HOSTS: |
        10.213.10.52 tcp.pcf21.starkandwayne.com
        10.213.10.3 api.pks.pcf21.starkandwayne.com
      





resources:
- name: osb-pks
  type: git
  source:
    branch: master
    uri: git@github.com:starkandwayne/osb-pks.git
    private_key: ((git_key))

