apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels: 
    release: "{{ .Release.Name }}"   
type: Opaque
data: 
  rabbitmq-username: {{ .Values.rabbitmqUsername | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmqPassword | b64enc | quote }}



